In [9]:
import pandas as pd

In [10]:
pdf = pd.read_csv('data/product_master_data.csv')
tdf = pd.read_csv('data/transactional_data.csv')

In [11]:
pdf

,Unnamed: 0,Product_ID,Product_Category,price$,storeID,supplierID,storeName,supplierName
0,0,P00069042,Home & Kitchen,77.51,2,13,Tech Haven,Samsung Electronics
1,1,P00248942,Grocery,9.63,6,9,Photo World,Canon Inc.
2,2,P00087842,Pets,31.66,4,18,Game Zone,Razer Inc.
3,3,P00085442,Pets,23.32,1,16,Electro Mart,Sony Corporation
4,4,P00285442,Toys,34.71,3,39,Sound Zone,Sonos Inc.
...,...,...,...,...,...,...,...,...
3626,545915,P00375436,Shoes,69.03,5,18,InnoTech,Razer Inc.
3627,545916,P00372445,Shoes,57.86,7,17,Health Zone,Garmin Ltd.
3628,545920,P00370293,Jewelry & Accessories,10.38,5,18,InnoTech,Razer Inc.
3629,545923,P00371644,Shoes,63.21,5,18,InnoTech,Razer Inc.
3630,545941,P00370853,Jewelry & Accessories,46.71,3,39,Sound Zone,Sonos Inc.

In [ ]:
pdf.isna().sum()

In [12]:
tdf

        Unnamed: 0  orderID  Customer_ID Product_ID  quantity        date
0                0  9914432      1000001  P00069042         1  2020-12-29
1                1  1676537      1000001  P00248942         3  2017-03-27
2                2  8910457      1000001  P00087842         1  2017-08-20
3                3  5044982      1000001  P00085442         1  2019-03-03
4                4  4176351      1000002  P00285442         1  2018-07-11
...            ...      ...          ...        ...       ...         ...
550063      550063  6404673      1006033  P00372445         2  2017-05-12
550064      550064  9816913      1006035  P00375436         2  2017-05-28
550065      550065  3633471      1006036  P00375436         2  2020-02-07
550066      550066  8866890      1006038  P00375436         3  2020-12-19
550067      550067  1711089      1006039  P00371644         2  2019-01-25

[550068 rows x 6 columns]

In [13]:
tdf.isna().sum()

Unnamed: 0     0
orderID        0
Customer_ID    0
Product_ID     0
quantity       0
date           0
dtype: int64

In [14]:
tdf['Product_ID'] = tdf['Product_ID'].str[1:]
tdf['Product_ID'] = tdf['Product_ID'].astype(int)
tdf

        Unnamed: 0  orderID  Customer_ID  Product_ID  quantity        date
0                0  9914432      1000001       69042         1  2020-12-29
1                1  1676537      1000001      248942         3  2017-03-27
2                2  8910457      1000001       87842         1  2017-08-20
3                3  5044982      1000001       85442         1  2019-03-03
4                4  4176351      1000002      285442         1  2018-07-11
...            ...      ...          ...         ...       ...         ...
550063      550063  6404673      1006033      372445         2  2017-05-12
550064      550064  9816913      1006035      375436         2  2017-05-28
550065      550065  3633471      1006036      375436         2  2020-02-07
550066      550066  8866890      1006038      375436         3  2020-12-19
550067      550067  1711089      1006039      371644         2  2019-01-25

[550068 rows x 6 columns]

In [15]:
tdf.isna().sum()

Unnamed: 0     0
orderID        0
Customer_ID    0
Product_ID     0
quantity       0
date           0
dtype: int64